# This playbook assumes that cyverse-ez-singularity directory is located in /opt/cyverse-ez-singularity/
# EJS Note 2/12/2019: ansible-galaxy fails ssl cert verify for galaxy.ansible.com/api. Can revert when fixed later

- name: this playbook will setup ez singularity locally
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: include variables found in /etc/cyverse/ez.yml, if it exists; if error, just ignore
      include_vars:
        file: /etc/cyverse/ez.yml
      ignore_errors: yes

    - name: remove the ez role if update is forced
      command: ansible-galaxy remove singularity
      when: ez_force_update is defined

    - name: pull in any Ansible Galaxy roles from the requirements.yml
      command: ansible-galaxy install -c -r /opt/cyverse-ez-singularity/requirements.yml

    - name: including cyverse ez role
      static: no
      include_role:
        name: singularity
